/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeTrocaEDevolucaoRouteImport } from './routes/politica-de-troca-e-devolucao'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCatalogoIndexRouteImport } from './routes/admin/catalogo/index'
import { Route as AdminCatalogoNovoRouteImport } from './routes/admin/catalogo/novo'
import { Route as AdminCatalogoIdEditarRouteImport } from './routes/admin/catalogo/$id/editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeTrocaEDevolucaoRoute =
  PoliticaDeTrocaEDevolucaoRouteImport.update({
    id: '/politica-de-troca-e-devolucao',
    path: '/politica-de-troca-e-devolucao',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoIndexRoute = AdminCatalogoIndexRouteImport.update({
  id: '/admin/catalogo/',
  path: '/admin/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoNovoRoute = AdminCatalogoNovoRouteImport.update({
  id: '/admin/catalogo/novo',
  path: '/admin/catalogo/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoIdEditarRoute = AdminCatalogoIdEditarRouteImport.update({
  id: '/admin/catalogo/$id/editar',
  path: '/admin/catalogo/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-troca-e-devolucao': typeof PoliticaDeTrocaEDevolucaoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/catalogo/novo': typeof AdminCatalogoNovoRoute
  '/admin/catalogo/': typeof AdminCatalogoIndexRoute
  '/admin/catalogo/$id/editar': typeof AdminCatalogoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-troca-e-devolucao': typeof PoliticaDeTrocaEDevolucaoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/catalogo/novo': typeof AdminCatalogoNovoRoute
  '/admin/catalogo': typeof AdminCatalogoIndexRoute
  '/admin/catalogo/$id/editar': typeof AdminCatalogoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-troca-e-devolucao': typeof PoliticaDeTrocaEDevolucaoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/catalogo/novo': typeof AdminCatalogoNovoRoute
  '/admin/catalogo/': typeof AdminCatalogoIndexRoute
  '/admin/catalogo/$id/editar': typeof AdminCatalogoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/loja'
    | '/politica-de-privacidade'
    | '/politica-de-troca-e-devolucao'
    | '/termos-de-uso'
    | '/admin/login'
    | '/admin/catalogo/novo'
    | '/admin/catalogo/'
    | '/admin/catalogo/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/loja'
    | '/politica-de-privacidade'
    | '/politica-de-troca-e-devolucao'
    | '/termos-de-uso'
    | '/admin/login'
    | '/admin/catalogo/novo'
    | '/admin/catalogo'
    | '/admin/catalogo/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/loja'
    | '/politica-de-privacidade'
    | '/politica-de-troca-e-devolucao'
    | '/termos-de-uso'
    | '/admin/login'
    | '/admin/catalogo/novo'
    | '/admin/catalogo/'
    | '/admin/catalogo/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LojaRoute: typeof LojaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDeTrocaEDevolucaoRoute: typeof PoliticaDeTrocaEDevolucaoRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminCatalogoNovoRoute: typeof AdminCatalogoNovoRoute
  AdminCatalogoIndexRoute: typeof AdminCatalogoIndexRoute
  AdminCatalogoIdEditarRoute: typeof AdminCatalogoIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-troca-e-devolucao': {
      id: '/politica-de-troca-e-devolucao'
      path: '/politica-de-troca-e-devolucao'
      fullPath: '/politica-de-troca-e-devolucao'
      preLoaderRoute: typeof PoliticaDeTrocaEDevolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogo/': {
      id: '/admin/catalogo/'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo/'
      preLoaderRoute: typeof AdminCatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogo/novo': {
      id: '/admin/catalogo/novo'
      path: '/admin/catalogo/novo'
      fullPath: '/admin/catalogo/novo'
      preLoaderRoute: typeof AdminCatalogoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogo/$id/editar': {
      id: '/admin/catalogo/$id/editar'
      path: '/admin/catalogo/$id/editar'
      fullPath: '/admin/catalogo/$id/editar'
      preLoaderRoute: typeof AdminCatalogoIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LojaRoute: LojaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDeTrocaEDevolucaoRoute: PoliticaDeTrocaEDevolucaoRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminCatalogoNovoRoute: AdminCatalogoNovoRoute,
  AdminCatalogoIndexRoute: AdminCatalogoIndexRoute,
  AdminCatalogoIdEditarRoute: AdminCatalogoIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
