/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeTrocaEDevolucaoRouteImport } from './routes/politica-de-troca-e-devolucao'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminConexoesRouteImport } from './routes/admin/conexoes'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMetricasRouteImport } from './routes/admin/metricas'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido/$orderId'
import { Route as ProdutoSlugRouteImport } from './routes/produto/$slug'
import { Route as AdminCatalogoIndexRouteImport } from './routes/admin/catalogo/index'
import { Route as AdminCatalogoNovoRouteImport } from './routes/admin/catalogo/novo'
import { Route as AdminCategoriasIndexRouteImport } from './routes/admin/categorias/index'
import { Route as AdminPedidosIndexRouteImport } from './routes/admin/pedidos/index'
import { Route as AdminCatalogoIdEditarRouteImport } from './routes/admin/catalogo/$id/editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeTrocaEDevolucaoRoute =
  PoliticaDeTrocaEDevolucaoRouteImport.update({
    id: '/politica-de-troca-e-devolucao',
    path: '/politica-de-troca-e-devolucao',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConexoesRoute = AdminConexoesRouteImport.update({
  id: '/admin/conexoes',
  path: '/admin/conexoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMetricasRoute = AdminMetricasRouteImport.update({
  id: '/admin/metricas',
  path: '/admin/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoIndexRoute = AdminCatalogoIndexRouteImport.update({
  id: '/admin/catalogo/',
  path: '/admin/catalogo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoNovoRoute = AdminCatalogoNovoRouteImport.update({
  id: '/admin/catalogo/novo',
  path: '/admin/catalogo/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriasIndexRoute = AdminCategoriasIndexRouteImport.update({
  id: '/admin/categorias/',
  path: '/admin/categorias/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosIndexRoute = AdminPedidosIndexRouteImport.update({
  id: '/admin/pedidos/',
  path: '/admin/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogoIdEditarRoute = AdminCatalogoIdEditarRouteImport.update({
  id: '/admin/catalogo/$id/editar',
  path: '/admin/catalogo/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-troca-e-devolucao': typeof PoliticaDeTrocaEDevolucaoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/conexoes': typeof AdminConexoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/catalogo/novo': typeof AdminCatalogoNovoRoute
  '/admin/catalogo/': typeof AdminCatalogoIndexRoute
  '/admin/categorias/': typeof AdminCategoriasIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/catalogo/$id/editar': typeof AdminCatalogoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-troca-e-devolucao': typeof PoliticaDeTrocaEDevolucaoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/conexoes': typeof AdminConexoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/catalogo/novo': typeof AdminCatalogoNovoRoute
  '/admin/catalogo': typeof AdminCatalogoIndexRoute
  '/admin/categorias': typeof AdminCategoriasIndexRoute
  '/admin/pedidos': typeof AdminPedidosIndexRoute
  '/admin/catalogo/$id/editar': typeof AdminCatalogoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/checkout': typeof CheckoutRoute
  '/loja': typeof LojaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/politica-de-troca-e-devolucao': typeof PoliticaDeTrocaEDevolucaoRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/conexoes': typeof AdminConexoesRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/metricas': typeof AdminMetricasRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/catalogo/novo': typeof AdminCatalogoNovoRoute
  '/admin/catalogo/': typeof AdminCatalogoIndexRoute
  '/admin/categorias/': typeof AdminCategoriasIndexRoute
  '/admin/pedidos/': typeof AdminPedidosIndexRoute
  '/admin/catalogo/$id/editar': typeof AdminCatalogoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/loja'
    | '/politica-de-privacidade'
    | '/politica-de-troca-e-devolucao'
    | '/termos-de-uso'
    | '/admin/conexoes'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/metricas'
    | '/pedido/$orderId'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/catalogo/novo'
    | '/admin/catalogo/'
    | '/admin/categorias/'
    | '/admin/pedidos/'
    | '/admin/catalogo/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/loja'
    | '/politica-de-privacidade'
    | '/politica-de-troca-e-devolucao'
    | '/termos-de-uso'
    | '/admin/conexoes'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/metricas'
    | '/pedido/$orderId'
    | '/produto/$slug'
    | '/admin'
    | '/admin/catalogo/novo'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/pedidos'
    | '/admin/catalogo/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/checkout'
    | '/loja'
    | '/politica-de-privacidade'
    | '/politica-de-troca-e-devolucao'
    | '/termos-de-uso'
    | '/admin/conexoes'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/metricas'
    | '/pedido/$orderId'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/catalogo/novo'
    | '/admin/catalogo/'
    | '/admin/categorias/'
    | '/admin/pedidos/'
    | '/admin/catalogo/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CheckoutRoute: typeof CheckoutRoute
  LojaRoute: typeof LojaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  PoliticaDeTrocaEDevolucaoRoute: typeof PoliticaDeTrocaEDevolucaoRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  AdminConexoesRoute: typeof AdminConexoesRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMetricasRoute: typeof AdminMetricasRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCatalogoNovoRoute: typeof AdminCatalogoNovoRoute
  AdminCatalogoIndexRoute: typeof AdminCatalogoIndexRoute
  AdminCategoriasIndexRoute: typeof AdminCategoriasIndexRoute
  AdminPedidosIndexRoute: typeof AdminPedidosIndexRoute
  AdminCatalogoIdEditarRoute: typeof AdminCatalogoIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-troca-e-devolucao': {
      id: '/politica-de-troca-e-devolucao'
      path: '/politica-de-troca-e-devolucao'
      fullPath: '/politica-de-troca-e-devolucao'
      preLoaderRoute: typeof PoliticaDeTrocaEDevolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conexoes': {
      id: '/admin/conexoes'
      path: '/admin/conexoes'
      fullPath: '/admin/conexoes'
      preLoaderRoute: typeof AdminConexoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/metricas': {
      id: '/admin/metricas'
      path: '/admin/metricas'
      fullPath: '/admin/metricas'
      preLoaderRoute: typeof AdminMetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogo/': {
      id: '/admin/catalogo/'
      path: '/admin/catalogo'
      fullPath: '/admin/catalogo/'
      preLoaderRoute: typeof AdminCatalogoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogo/novo': {
      id: '/admin/catalogo/novo'
      path: '/admin/catalogo/novo'
      fullPath: '/admin/catalogo/novo'
      preLoaderRoute: typeof AdminCatalogoNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categorias/': {
      id: '/admin/categorias/'
      path: '/admin/categorias'
      fullPath: '/admin/categorias/'
      preLoaderRoute: typeof AdminCategoriasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos/': {
      id: '/admin/pedidos/'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos/'
      preLoaderRoute: typeof AdminPedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalogo/$id/editar': {
      id: '/admin/catalogo/$id/editar'
      path: '/admin/catalogo/$id/editar'
      fullPath: '/admin/catalogo/$id/editar'
      preLoaderRoute: typeof AdminCatalogoIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  CheckoutRoute: CheckoutRoute,
  LojaRoute: LojaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  PoliticaDeTrocaEDevolucaoRoute: PoliticaDeTrocaEDevolucaoRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  AdminConexoesRoute: AdminConexoesRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMetricasRoute: AdminMetricasRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCatalogoNovoRoute: AdminCatalogoNovoRoute,
  AdminCatalogoIndexRoute: AdminCatalogoIndexRoute,
  AdminCategoriasIndexRoute: AdminCategoriasIndexRoute,
  AdminPedidosIndexRoute: AdminPedidosIndexRoute,
  AdminCatalogoIdEditarRoute: AdminCatalogoIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
