-- Bucket for images generated by Admin > Marketing > Ideias de Post. Public read (same pattern as
-- product-media) so a downloaded/shared image URL just works; writes only ever happen server-side
-- via generate-post-ideas (service role, bypasses RLS) — the admin insert/update/delete policies
-- below exist for parity with product-media and to allow a future admin-side cleanup action.
insert into storage.buckets (id, name, public)
values ('post-ideas', 'post-ideas', true)
on conflict (id) do nothing;

create policy post_ideas_public_read on storage.objects
  for select using (bucket_id = 'post-ideas');

create policy post_ideas_admin_insert on storage.objects
  for insert with check (bucket_id = 'post-ideas' and has_role(auth.uid(), 'admin'::app_role));

create policy post_ideas_admin_update on storage.objects
  for update using (bucket_id = 'post-ideas' and has_role(auth.uid(), 'admin'::app_role));

create policy post_ideas_admin_delete on storage.objects
  for delete using (bucket_id = 'post-ideas' and has_role(auth.uid(), 'admin'::app_role));
